name: Build & Tests

on:
  push:
    branches:  '**'
  pull_request:
    branches:  '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt;
    - name: Test with unittest and coverage-report
      run: |
        flask test --coverage
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: "9c14be86-4bc7-4f29-93e5-3e56297e6325"
        fail_ci_if_error: true
        files: ./coverage.xml
        directory: ./tmp/coverage
        flags: unittests